version: '3'
services:
  backend:
    container_name: sqlite_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
     - "5001:5001"

  frontend:
    container_name: sqlite_frontend  
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
     - "8080:8080"